create table public.users
(
    id            integer generated by default as identity
        constraint pk_users
            primary key,
    email_address varchar(320) not null
        constraint uc_users_email_address
            unique,
    password      varchar(25)  not null
);

alter table public.users
    owner to postgres;

create table public.candidates
(
    id                    integer     not null
        constraint pk_candidates
            primary key
        constraint fk_candidates_users
            references public.users
            on delete cascade,
    first_name            varchar(35) not null,
    last_name             varchar(35) not null,
    identification_number varchar(11) not null
        constraint uc_candidates_identification_number
            unique,
    birth_date            date        not null
);

alter table public.candidates
    owner to postgres;

create table public.employers
(
    id           integer      not null
        constraint pk_employers
            primary key
        constraint fk_employers_users
            references public.users
            on delete cascade,
    company_name varchar(255) not null,
    web_address  varchar(255) not null,
    constraint chk_employers_web_address
        check (validate_email_by_domain(id, web_address))
);

alter table public.employers
    owner to postgres;

create table public.employer_phones
(
    id           integer generated by default as identity
        constraint pk_employer_phones
            primary key,
    employer_id  integer     not null
        constraint fk_employer_phones_employer_id
            references public.employers
            on delete cascade,
    phone_number varchar(12) not null
);

alter table public.employer_phones
    owner to postgres;

create table public.employees
(
    id         integer     not null
        constraint pk_employees
            primary key
        constraint fk_employees_users
            references public.users
            on delete cascade,
    first_name varchar(35) not null,
    last_name  varchar(35) not null
);

alter table public.employees
    owner to postgres;

create table public.verification_codes
(
    id          integer generated by default as identity
        constraint pk_verification_codes
            primary key,
    code        varchar(38)           not null
        constraint uc_verification_codes_is_verified
            unique,
    is_verified boolean default false not null
);

alter table public.verification_codes
    owner to postgres;

create table public.verification_codes_candidates
(
    id           integer not null
        constraint pk_verification_codes_candidates
            primary key
        constraint fk_verification_codes_candidates_verification_codes
            references public.verification_codes
            on delete cascade,
    candidate_id integer not null
        constraint fk_verification_codes_candidates_candidates
            references public.candidates
            on delete cascade
);

alter table public.verification_codes_candidates
    owner to postgres;

create table public.verification_codes_employers
(
    id          integer not null
        constraint pk_verification_codes_employers
            primary key
        constraint fk_verification_codes_employers_verification_codes
            references public.verification_codes
            on delete cascade,
    employer_id integer not null
        constraint fk_verification_codes_employers_employers
            references public.employers
            on delete cascade
);

alter table public.verification_codes_employers
    owner to postgres;

create table public.employee_confirms
(
    id           integer generated by default as identity
        constraint pk_employee_confirms
            primary key,
    employee_id  integer               not null
        constraint fk_employee_confirms_employees
            references public.employees
            on delete cascade,
    is_confirmed boolean default false not null
);

alter table public.employee_confirms
    owner to postgres;

create table public.employee_confirms_employers
(
    id          integer not null
        constraint pk_employee_confirms_employers
            primary key
        constraint fk_employee_confirms_employers_employee_confirms
            references public.employee_confirms
            on delete cascade,
    employer_id integer not null
        constraint fk_employee_confirms_employers_employers
            references public.employers
            on delete cascade
);

alter table public.employee_confirms_employers
    owner to postgres;

create table public.job_titles
(
    id    integer generated by default as identity
        constraint pk_job_titles
            primary key,
    title varchar(255) not null
        constraint uc_job_titles_title
            unique
);

alter table public.job_titles
    owner to postgres;

